require('dotenv').config()

const BLOCK_CHAIN_URL = process.env.BLOCK_CHAIN_URL;
const BLOCK_CHAIN_CONTRACT = process.env.BLOCK_CHAIN_CONTRACT;
const DELEGATE_DURATION = process.env.BLOCK_CHAIN_DELEGATE_DURATION || 1300000;
const ATTRIBUTE_VALIDITY = process.env.BLOCK_CHAIN_ATTRIBUTE_VALIDITY || 1300000;

module.exports = {
  BLOCKCHAIN: {
    BLOCK_CHAIN_URL: BLOCK_CHAIN_URL,
    BLOCK_CHAIN_CONTRACT: BLOCK_CHAIN_CONTRACT,
    DELEGATE_DURATION: DELEGATE_DURATION,
    ATTRIBUTE_VALIDITY: ATTRIBUTE_VALIDITY
  }
}