require('dotenv').config()

const BLOCK_CHAIN_URL = process.env.BLOCK_CHAIN_URL;
const BLOCK_CHAIN_CONTRACT = process.env.BLOCK_CHAIN_CONTRACT;
const DELEGATE_DURATION = process.env.BLOCK_CHAIN_DELEGATE_DURATION || 1300000;
const ATTRIBUTE_VALIDITY = process.env.BLOCK_CHAIN_ATTRIBUTE_VALIDITY || 1300000;


// Test constants
const TEST_ISSUER_DID = process.env.TEST_ISSUER_DID || "did:ethr:0xfddb211f40df15e69b400566e59c89f2728ea41f";
const TEST_ISSUER_PRIV_KEY = process.env.TEST_ISSUER_PRIV_KEY || "6c7c7d94c543b949bb2f6c8627d32dedf9ecba5e818fa776c39b03f797a81d0d";

module.exports = {
  BLOCKCHAIN: {
    BLOCK_CHAIN_URL: BLOCK_CHAIN_URL,
    BLOCK_CHAIN_CONTRACT: BLOCK_CHAIN_CONTRACT,
    DELEGATE_DURATION: DELEGATE_DURATION,
    ATTRIBUTE_VALIDITY: ATTRIBUTE_VALIDITY
  },

  TESTS: {
    ISSUER_IDENTITY: {
      DID: TEST_ISSUER_DID,
      PRIV_KEY: TEST_ISSUER_PRIV_KEY
    }
  }
}